In [ ]:
import numpy as np

In [ ]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [ ]:
np.random.rand(3,4)

array([[0.98886584, 0.19683959, 0.26131564, 0.69769819],
       [0.40479822, 0.58237039, 0.35410062, 0.06591491],
       [0.43983147, 0.87051625, 0.65922918, 0.39692658]])

In [ ]:
print(np.zeros((3,3)))

print(np.ones((4,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.random.rand(6,3).T

array([[0.35956635, 0.69466368, 0.79575248, 0.83895514, 0.56032562,
        0.17020114],
       [0.01699482, 0.17953771, 0.22795634, 0.5700157 , 0.27614929,
        0.07927598],
       [0.57838388, 0.90139001, 0.51856471, 0.08548819, 0.05543873,
        0.05639006]])

In [ ]:
arr1 = np.random.rand(3,4)
arr2 = np.random.rand(4,5)

dot_1_2 = np.dot(arr1, arr2)
print(dot_1_2)

[[0.37801189 0.43773643 0.64339296 0.83667855 0.48701178]
 [0.97888769 0.87239706 1.28467661 1.43922483 0.81267614]
 [0.75238827 1.14920532 1.06122605 0.80004664 0.64927913]]


In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [12]:
%cd /content/drive/MyDrive

/content/drive/MyDrive


In [13]:
%cd git_repos

/content/drive/MyDrive/git_repos


In [14]:
!git config --global user.email "25006171@siswa.um.edu.my"
!git config --global user.name "JonathanSia-2025"

In [15]:
!mv "../../Colab Notebooks/Tutorial3.ipynb" "./"

mv: cannot stat '../../Colab Notebooks/Tutorial3.ipynb': No such file or directory


In [16]:
!git status

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
